# Generated by Django 5.1.1 on 2024-11-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(default='Sin descripción', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Nombre no disponible', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='url_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
