# Generated by Django 5.1.1 on 2024-11-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock_description_stock_name_stock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
