# Generated by Django 5.1.1 on 2024-11-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
