# Generated by Django 5.1.1 on 2024-11-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
