# Generated by Django 5.1.1 on 2024-11-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_tax_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tax_regime',
            field=models.CharField(blank=True, choices=[('autoretenedor', 'Autoretenedor'), ('regimen_simplificado', 'Régimen Simplificado')], max_length=150, null=True),
        ),
    ]
