# Generated by Django 5.1.1 on 2024-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_tax_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='social_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
