# Generated by Django 5.1.1 on 2024-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_sales_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
