# Generated by Django 5.1.1 on 2024-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
