# Generated by Django 5.1.1 on 2024-10-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producthistory_city_producthistory_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'verbose_name': 'Product history', 'verbose_name_plural': 'Product histories'},
        ),
    ]
